on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Run tests
        run: go test ./...
